import React, { useState, useEffect, useCallback } from "react";
import { useCandidates } from "./hooks/useCandidates";
import { CandidateList } from "./CandidateList";
import { GenerationSelector } from "./GenerationSelector";
import { Toaster } from "./ui/sonner";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { Card, CardContent } from "./ui/card";
import { AlertTriangle } from "lucide-react";
import type { CandidateEditState } from "../types";

export function CandidatesPage() {
  const [generationId, setGenerationId] = useState<string | null>(null);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const urlParams = new URLSearchParams(window.location.search);
      setGenerationId(urlParams.get("generation_id"));
    }
  }, []);

  const { candidates, loading, error, hasMore, loadMore, updateCandidate, acceptCandidate, rejectCandidate } =
    useCandidates(generationId || undefined);

  const [editState, setEditState] = useState<CandidateEditState | null>(null);

  const handleEditStart = (candidateId: string, front: string, back: string) => {
    setEditState({
      candidateId,
      isEditing: true,
      tempFront: front,
      tempBack: back,
      errors: [],
    });
  };

  const handleAccept = useCallback(
    async (candidateId: string) => {
      await acceptCandidate(candidateId);
    },
    [acceptCandidate]
  );

  const handleEditSave = async (candidateId: string, changes: { front: string; back: string }) => {
    const errors = validateEdit(changes.front, changes.back);
    if (errors.length > 0) {
      setEditState(editState ? { ...editState, errors } : null);
      return;
    }

    try {
      await updateCandidate(candidateId, {
        front: changes.front,
        back: changes.back,
        status: "edited",
      });
      setEditState(null);
    } catch {
      // Error handled by hook
    }
  };

  const handleEditCancel = () => {
    setEditState(null);
  };

  const validateEdit = (front: string, back: string): string[] => {
    const errors: string[] = [];
    if (front.length > 200) {
      errors.push("Question cannot exceed 200 characters");
    }
    if (back.length > 500) {
      errors.push("Answer cannot exceed 500 characters");
    }
    if (front.trim().length === 0) {
      errors.push("Question cannot be empty");
    }
    if (back.trim().length === 0) {
      errors.push("Answer cannot be empty");
    }
    return errors;
  };

  const handleSelectGeneration = (selectedGenerationId: string) => {
    const url = new URL(window.location.href);
    url.searchParams.set("generation_id", selectedGenerationId);
    window.history.pushState({}, "", url.toString());
    setGenerationId(selectedGenerationId);
  };

  if (!generationId) {
    return (
      <div className="space-y-8 max-w-7xl mx-auto">
        <div className="text-center space-y-3">
          <h1 className="text-4xl font-bold tracking-tight">AI Candidates</h1>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Review and manage flashcards generated by AI
          </p>
        </div>

        <Card className="shadow-sm">
          <CardContent className="flex items-center justify-center py-12">
            <div className="text-center">
              <p className="text-muted-foreground text-lg">No generation selected</p>
              <p className="text-sm text-muted-foreground mt-2">
                Please select a generation to view its candidates. You can do this by:
              </p>
              <ul className="text-sm text-muted-foreground mt-4 space-y-1">
                <li>• Going to the generator page to create new flashcards</li>
                <li>
                  • Adding <code className="bg-muted px-1 py-0.5 rounded">?generation_id=UUID</code> to the URL
                </li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <GenerationSelector onSelectGeneration={handleSelectGeneration} />

        <Toaster />
      </div>
    );
  }

  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      <div className="text-center space-y-3">
        <h1 className="text-4xl font-bold tracking-tight">AI Candidates</h1>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">Review and manage flashcards generated by AI</p>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>
            <div className="space-y-2">
              <p>{error.error.message}</p>
              {error.error.code === "not_found" && (
                <div className="text-sm text-muted-foreground">
                  <p>This generation may have been deleted or the link might be incorrect.</p>
                  <p className="mt-2">
                    Try going back to the{" "}
                    <a href="/generator" className="text-primary hover:underline">
                      generator page
                    </a>{" "}
                    to create new flashcards.
                  </p>
                </div>
              )}
            </div>
          </AlertDescription>
        </Alert>
      )}

      <CandidateList
        candidates={candidates}
        loading={loading}
        hasMore={hasMore}
        editState={editState}
        onEditStart={handleEditStart}
        onEditSave={handleEditSave}
        onEditCancel={handleEditCancel}
        onAccept={handleAccept}
        onReject={rejectCandidate}
        onLoadMore={loadMore}
      />

      <Toaster />
    </div>
  );
}
