-- extend allowed source kinds with documentation & notes and seed default records
begin;

alter table public.sources
    drop constraint if exists sources_kind_check;

alter table public.sources
    add constraint sources_kind_check
        check (kind in ('book', 'article', 'course', 'url', 'other', 'documentation', 'notes'));

insert into public.sources (name, slug, description, kind, url)
values
    (
        'Documentation',
        'documentation',
        'Official documentation for technologies and frameworks',
        'documentation',
        null
    ),
    (
        'Manual Notes',
        'manual-notes',
        'Personal notes and study materials',
        'notes',
        null
    ),
    (
        'Articles',
        'articles',
        'Articles and tutorials from various sources',
        'article',
        null
    ),
    (
        'AI',
        'ai',
        'Content generated by artificial intelligence',
        'other',
        null
    ),
    (
        'Books',
        'books',
        'Materials from books and book publications',
        'book',
        null
    ),
    (
        'Vocabulary',
        'vocabulary',
        'Vocabulary and language expressions',
        'other',
        null
    )
on conflict (slug) do update
set
    description = excluded.description,
    kind = excluded.kind,
    url = excluded.url,
    updated_at = timezone('utc', now());

commit;

